# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18NF8wOqdvvd_3-Wkoc22Hp1MdaFPm2t7
"""

import pandas as pd
lst = ['Greek', 'For', 'Greek','is', 'portal', 'for', 'Greek']
df = pd.DataFrame(lst)
print(df)

import pandas as pd
data = {'Name':['Tom','nick','Krish','jack'],
        'Age':[20,21,19,18]}

df = pd.DataFrame(data)

print(df)

import pandas as pd
data = {'Name':['Tom','nick','Krish','jack'],
        'Age':[20,21,19,18]}

df = pd.DataFrame(data)
print(df)

import statistics

nums = [10, 20, 20, 30, 40, 50]

mean_val = statistics.mean(nums)
median_val = statistics.median(nums)
mode_val = statistics.mode(nums)
variance_val = statistics.variance(nums)
std_dev = statistics.stdev(nums)

print("Mean:", mean_val)
print("Median:", median_val)
print("Mode:", mode_val)
print("Variance:", variance_val)
print("Standard Deviation:", std_dev)

import numpy as np

arr = np.array([1,2,3,4,5,6])

# Sum and mean
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))

# Max and min
print("Max:", np.max(arr))
print("Min:", np.min(arr))

# Reshape
reshaped = arr.reshape(2,3)
print("Reshaped array:\n", reshaped)

# Element-wise multiplication
mul = arr * 2
print("Element-wise multiplication:\n", mul)

import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

# Addition
print("Addition:\n", A + B)

# Subtraction
print("Subtraction:\n", A - B)

# Matrix multiplication
print("Matrix Multiplication:\n", np.dot(A,B))

# Transpose
print("Transpose of A:\n", A.T)

import numpy as np

rand_arr = np.random.rand(10)

print("Array:", rand_arr)
print("Mean:", np.mean(rand_arr))
print("Std Dev:", np.std(rand_arr))
print("Min:", np.min(rand_arr))
print("Max:", np.max(rand_arr))

from scipy import stats

data1 = [10, 12, 14, 16, 18]
data2 = [11, 13, 15, 17, 19]

# Mean using scipy
print("Mean:", stats.tmean(data1))

# t-test
t_stat, p_val = stats.ttest_ind(data1, data2)
print("T-statistic:", t_stat)
print("P-value:", p_val)

from scipy import integrate

def func(x):
    return x**2

result, error = integrate.quad(func, 0, 3)

print("Integration Result:", result)
print("Estimated Error:", error)

data = {'Name':['Shreyash', 'Shreyansh','Tarun'],
        'Age':[22,22,21],
        'Address':['Prayagraj','Ayodhya','Aligarh'],
        'Qualification':['Btech','MCA','BCA']}
df = pd.DataFrame(data)
print(df[['Name','Qualification','Address']])

import pandas as pd
data = pd.read_csv("/content/nba.csv",index_col="Name")

first = data.loc["Avery Bradley"]
second  = data.loc["R.J. Hunter"]

print(first , "\n\n\n", second)

import numpy as np
import matplotlib.pyplot as plt

# Generate random data
np.random.seed(42)
x = 2 * np.random.rand(100, 1)
y = 4 + 3 * x + np.random.randn(100, 1)

# Add bias term (1) for intercept
X_b = np.c_[np.ones((100, 1)), x]

# Normal Equation to calculate theta
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

print("Intercept (theta0):", theta_best[0][0])
print("Slope (theta1):", theta_best[1][0])

# Predict values
x_new = np.array([[0], [2]])
x_new_b = np.c_[np.ones((2, 1)), x_new]
y_predict = x_new_b.dot(theta_best)

# Plot
plt.scatter(x, y)
plt.plot(x_new, y_predict)
plt.xlabel("X")
plt.ylabel("Y")
plt.title("Linear Regression Curve")
plt.show()